/*
 * Copyright 2018 JBoss by Red Hat.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.optaplanner.examples.nurserostering.swingui;

import javax.swing.ListSelectionModel;

/**
 *
 * @author Martien
 */
public class TabShiftTypePanel extends javax.swing.JPanel {

    /**
     * Creates new form TabShiftTypePanel
     */
    public TabShiftTypePanel() {
        initComponents();
    }
    
    public void handleOKButtonClicked(){
    //Override in customTabShiftTypePanel
    }
    
    public void handleCancelButtonClicked(){
    //Override in customTabShiftTypePanel
    }
    
    public void handleNewButtonClicked(){
    //Override in customTabShiftTypePanel
    }
    
    public void handleDeleteButtonClicked(){
    //Override in customTabShiftTypePanel   
    };
 
    
    public void handleShiftTypeListValueChanged(javax.swing.event.ListSelectionEvent evt){
    //Override in customTabShiftTypePanel
    }
    
    public void emptyListBox(){
        String[] listData = null;
        jShiftTypeList.setListData(listData);
    }
    
    public void setListBox(String[] listData){
        jShiftTypeList.setListData(listData);
    }
    
    public void setListBoxMode() {
        jShiftTypeList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void setShiftTypeListBoxSelection(int selection){
        jShiftTypeList.setSelectedIndex(selection);
    }
    
    public ListSelectionModel getListSelectionModel(){
        return jShiftTypeList.getSelectionModel();
    }
    
    public String getCode(){
        return jCodeTextField.getText();
    }
    
    public void setCode(String text){
        jCodeTextField.setText(text);
    }
    
    public String getIndex(){
        return jIndexTextField.getText();
    }
    
    public void setIndex(String text){
        jIndexTextField.setText(text);
    }
    
    public Boolean getNight(){
        return jNightTextField.getText().equals(true);
    }
    
    public void setNight(Boolean text){
        jNightTextField.setText(text.toString());
    }
    
    public String getStartTime(){
        return jStartTimeTextField.getText();
    }
    
    public void setStartTime(String text){
        jStartTimeTextField.setText(text);
    }
    
    public String getEndTime(){
        return jEndTimeTextField.getText();
    }
    
    public void setEndTime(String text){
        jEndTimeTextField.setText(text);
    }
    
    public String getDescription(){
        return jDescriptionTextField.getText();
    }
    
    public void setDescription(String text){
        jDescriptionTextField.setText(text);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCodeLabel = new javax.swing.JLabel();
        jIndexLabel = new javax.swing.JLabel();
        jNightLabel = new javax.swing.JLabel();
        jStartTimeLabel = new javax.swing.JLabel();
        jEndTimeLabel = new javax.swing.JLabel();
        jDescriptionLabel = new javax.swing.JLabel();
        jOKButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();
        jNewButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jShiftTypeList = new javax.swing.JList<>();
        jCodeTextField = new javax.swing.JTextField();
        jIndexTextField = new javax.swing.JTextField();
        jNightTextField = new javax.swing.JTextField();
        jEndTimeTextField = new javax.swing.JTextField();
        jStartTimeTextField = new javax.swing.JTextField();
        jDescriptionTextField = new javax.swing.JTextField();
        jDeleteButton = new javax.swing.JButton();

        jLabel1.setText("ShiftType");

        jCodeLabel.setText("Code");

        jIndexLabel.setText("Index");

        jNightLabel.setText("Night");

        jStartTimeLabel.setText("StartTime");

        jEndTimeLabel.setText("EndTime");

        jDescriptionLabel.setText("description");

        jOKButton.setText("OK");
        jOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKButtonActionPerformed(evt);
            }
        });

        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jNewButton.setText("New");
        jNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewButtonActionPerformed(evt);
            }
        });

        jShiftTypeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jShiftTypeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jShiftTypeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jShiftTypeListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jShiftTypeList);

        jCodeTextField.setText("code");

        jIndexTextField.setText("index");

        jNightTextField.setText("night");

        jEndTimeTextField.setText("endTime");

        jStartTimeTextField.setText("startTime");

        jDescriptionTextField.setText("description");

        jDeleteButton.setText("Delete");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jIndexLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jIndexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCodeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jNightLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jNightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDescriptionLabel)
                                .addGap(45, 45, 45)
                                .addComponent(jDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jStartTimeLabel)
                                        .addGap(55, 55, 55))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jEndTimeLabel)
                                        .addGap(60, 60, 60)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jEndTimeTextField)
                                    .addComponent(jStartTimeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jOKButton)
                            .addComponent(jLabel1)
                            .addComponent(jNewButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDeleteButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCancelButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodeLabel)
                    .addComponent(jCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStartTimeLabel)
                    .addComponent(jStartTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jIndexLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jEndTimeLabel)
                        .addComponent(jEndTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jIndexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNightLabel)
                    .addComponent(jDescriptionLabel)
                    .addComponent(jNightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewButton)
                    .addComponent(jDeleteButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOKButton)
                    .addComponent(jCancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        // TODO add your handling code here:
        handleCancelButtonClicked();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKButtonActionPerformed
        // TODO add your handling code here:
        handleOKButtonClicked();
    }//GEN-LAST:event_jOKButtonActionPerformed

    private void jNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewButtonActionPerformed
        // TODO add your handling code here:
        handleNewButtonClicked();
    }//GEN-LAST:event_jNewButtonActionPerformed

    private void jShiftTypeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jShiftTypeListValueChanged
        // TODO add your handling code here:
        handleShiftTypeListValueChanged(evt);
    }//GEN-LAST:event_jShiftTypeListValueChanged

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        // TODO add your handling code here:
        handleDeleteButtonClicked();
    }//GEN-LAST:event_jDeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelButton;
    private javax.swing.JLabel jCodeLabel;
    private javax.swing.JTextField jCodeTextField;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JLabel jDescriptionLabel;
    private javax.swing.JTextField jDescriptionTextField;
    private javax.swing.JLabel jEndTimeLabel;
    private javax.swing.JTextField jEndTimeTextField;
    private javax.swing.JLabel jIndexLabel;
    private javax.swing.JTextField jIndexTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jNewButton;
    private javax.swing.JLabel jNightLabel;
    private javax.swing.JTextField jNightTextField;
    private javax.swing.JButton jOKButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jShiftTypeList;
    private javax.swing.JLabel jStartTimeLabel;
    private javax.swing.JTextField jStartTimeTextField;
    // End of variables declaration//GEN-END:variables
}
